version: '3.8'

services:
  # Keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    command: start-dev
    ports:
      - "8082:8080"  # Expose Keycloak on port 8082
    depends_on:
      - keycloak-db
    networks:
      - ecommerce-network  # Connect to the network

  keycloak-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"  # Expose PostgreSQL for Keycloak on port 5433
    networks:
      - ecommerce-network  # Connect to the network

  eureka-server:
    build:
      context: ./eureka-server  # Path to the Dockerfile
    ports:
      - "8761:8761"  # Expose Eureka on port 8761
    networks:
      - ecommerce-network  # Connect to the network

  gateway-service:
    build:
      context: ./gateway-service  # Path to the Dockerfile
    ports:
      - "8080:8080"  # Expose Gateway on port 8080
    depends_on:
      - eureka-server
      - keycloak  # Dependency on Keycloak
    networks:
      - ecommerce-network  # Connect to the network

  user-service:
    build:
      context: ./user-service  # Path to the Dockerfile
    ports:
      - "8081:8081"  # Expose User Service on port 8081
    depends_on:
      - eureka-server
      - keycloak  # Dependency on Keycloak
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://keycloak-db:5432/userdb  # Path to the database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - ecommerce-network  # Connect to the network

networks:
  ecommerce-network:
    driver: bridge  # Use bridge network
