app:
  name: gateway # change
  hostname: localhost # change
  server-port: 8181
  eureka:
    hostname: localhost # change
    port: 8761
  version: v1
  user-service:
    name: user
    context-path: api/${app.user-service.name}/${app.version}
  keycloak:
    hostname: localhost # change
    port: 8082

security:
  enabled: true
  skip-urls:
    - /eureka/**
    - /actuator/**
    - /${app.user-service.context-path}/**
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.keycloak.hostname}:${app.keycloak.port}/realms/EcommerceSEAL
          jwk-set-uri: http://${app.keycloak.hostname}:${app.keycloak.port}/realms/EcommerceSEAL/protocol/openid-connect/certs
cloud:
  gateway:
    globalcors:
      '[/**]':
        allowedOrigins: "*"
        allowedMethods: "*"
    discovery:
      locator:
        enabled: true
    default-filters:
      - TokenRelay
    routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/api/user/**

server:
  port: ${app.server-port}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka.hostname}:${app.eureka.port}/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5