app:
    name: user
    hostname: localhost
    ereka:
        hostname: localhost
        port: 8761
    server:
      port: 8081

spring:
  application:
    name: ${app.name}-service

eureka:
  client:
    service-url:
      defaultZone: http://${app.ereka.hostname}:${app.ereka.port}/eureka/
